# Generated by Django 5.2.14 on 2026-05-21 10:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Position',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categorie', models.CharField(max_length=50)),
                ('nom_poste', models.CharField(max_length=50)),
                ('code_poste', models.CharField(blank=True, max_length=10, null=True, unique=True)),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positions',
                'ordering': ['categorie', 'nom_poste'],
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_sport', models.CharField(max_length=50, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Sport',
                'verbose_name_plural': 'Sports',
                'ordering': ['nom_sport'],
            },
        ),
        migrations.CreateModel(
            name='RecruiterProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('organisation', models.CharField(blank=True, max_length=150, null=True)),
                ('poste_occupe', models.CharField(blank=True, max_length=100, null=True)),
                ('telephone', models.CharField(blank=True, max_length=20, null=True)),
                ('is_validated', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='recruiter_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Profil Recruteur',
                'verbose_name_plural': 'Profils Recruteurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_complet', models.CharField(max_length=100)),
                ('date_naissance', models.DateField()),
                ('ville', models.CharField(max_length=100)),
                ('pied_fort', models.CharField(choices=[('droit', 'Droit'), ('gauche', 'Gauche'), ('ambidextre', 'Ambidextre')], default='droit', max_length=15)),
                ('taille', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('poids', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('statut_club', models.CharField(choices=[('club_officiel', 'Club Officiel'), ('centre_formation', 'Centre de Formation'), ('groupe_travail', 'Groupe de Travail')], default='groupe_travail', max_length=25)),
                ('nom_club', models.CharField(blank=True, max_length=150, null=True)),
                ('whatsapp', models.CharField(max_length=20)),
                ('photo_profil', models.ImageField(blank=True, null=True, upload_to='photos/profils/')),
                ('identity_doc', models.FileField(blank=True, null=True, upload_to='documents/identite/')),
                ('is_verified', models.BooleanField(default=False)),
                ('is_published', models.BooleanField(default=False)),
                ('is_minor', models.BooleanField(default=False)),
                ('tuteur_nom', models.CharField(blank=True, max_length=100, null=True)),
                ('tuteur_lien', models.CharField(blank=True, choices=[('pere', 'Père'), ('mere', 'Mère'), ('tuteur_legal', 'Tuteur Légal'), ('autre', 'Autre Responsable')], max_length=20, null=True)),
                ('tuteur_whatsapp', models.CharField(blank=True, max_length=20, null=True)),
                ('consent_doc', models.FileField(blank=True, null=True, upload_to='documents/consentements/')),
                ('is_minor_consent_validated', models.BooleanField(default=False)),
                ('consent_validated_at', models.DateTimeField(blank=True, null=True)),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('profile_views', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('consent_validated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='validated_consents', to=settings.AUTH_USER_MODEL)),
                ('position', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_principal', to='profiles.position')),
                ('position_secondaire', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles_secondaire', to='profiles.position')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
                ('sport', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profiles', to='profiles.sport')),
            ],
            options={
                'verbose_name': 'Profil Joueur',
                'verbose_name_plural': 'Profils Joueurs',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='position',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positions', to='profiles.sport'),
        ),
        migrations.AlterUniqueTogether(
            name='position',
            unique_together={('sport', 'categorie', 'nom_poste')},
        ),
    ]
