# Generated by Django 5.2.14 on 2026-05-21 10:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('profiles', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('photo', 'Photo'), ('video_link', 'Lien Vidéo'), ('video_file', 'Fichier Vidéo')], max_length=20)),
                ('url', models.URLField(blank=True, max_length=500, null=True)),
                ('fichier', models.FileField(blank=True, null=True, upload_to='videos/')),
                ('thumbnail_url', models.URLField(blank=True, max_length=500, null=True)),
                ('order_index', models.PositiveSmallIntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medias', to='profiles.profile')),
            ],
            options={
                'verbose_name': 'Media',
                'verbose_name_plural': 'Medias',
                'ordering': ['order_index', 'created_at'],
            },
        ),
    ]
